services:
  postgres:
    image: postgres:15-alpine
    container_name: portfolio-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: praneeth
      POSTGRES_PASSWORD: praneeth123
      POSTGRES_DB: portfolio
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - portfolio-network

  mongo:
    image: mongo:7-jammy
    container_name: portfolio-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: praneeth
      MONGO_INITDB_ROOT_PASSWORD: praneeth123
      MONGO_INITDB_DATABASE: portfolio
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - portfolio-network

  redis:
    image: redis:7-alpine
    container_name: portfolio-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge

volumes:
  postgres_data:
  mongo_data:
